/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import backend.GameManagerBE;
import backend.PlayerManagerBE;
import backend.TeamManagerBE;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class AddMatchResults extends javax.swing.JFrame {

    /**
     * Creates new form AddMatchResults
     */
    public AddMatchResults() {
        try {
            initComponents();

            DefaultComboBoxModel comboMod = new DefaultComboBoxModel(TeamManagerBE.getRHBTeamNames().toArray());
            TeamACombo.setModel(comboMod);
            updatePlayers();

            DefaultComboBoxModel oppComboMod = new DefaultComboBoxModel(TeamManagerBE.getOpponentTeamNames().toArray());
            TeamBCombo.setModel(oppComboMod);

            String[] location = {"Home", "Away"};
            DefaultComboBoxModel posmodel = new DefaultComboBoxModel();
            for (int i = 0; i < location.length; i++) {
                posmodel.addElement(location[i]);
            }
            LocationCombo.setModel(posmodel);

        } catch (SQLException ex) {
            Logger.getLogger(AddMatchResults.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddMatchResults.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // updates all plaercombos to the corrseponding team
    private void updatePlayers() throws SQLException, ClassNotFoundException {

        String teamName = (String) TeamACombo.getSelectedItem();
        String teamID = TeamManagerBE.getTeamID(teamName).replace("#", "");

        DefaultComboBoxModel players1 = new DefaultComboBoxModel();
        DefaultComboBoxModel players2 = new DefaultComboBoxModel();
        DefaultComboBoxModel players3 = new DefaultComboBoxModel();
        DefaultComboBoxModel players4 = new DefaultComboBoxModel();
        DefaultComboBoxModel players5 = new DefaultComboBoxModel();
        DefaultComboBoxModel players6 = new DefaultComboBoxModel();
        DefaultComboBoxModel players7 = new DefaultComboBoxModel();
        DefaultComboBoxModel players8 = new DefaultComboBoxModel();
        DefaultComboBoxModel players9 = new DefaultComboBoxModel();
        DefaultComboBoxModel players10 = new DefaultComboBoxModel();
        players1.addElement("");
        players2.addElement("");
        players3.addElement("");
        players4.addElement("");
        players5.addElement("");
        players6.addElement("");
        players7.addElement("");
        players8.addElement("");
        players9.addElement("");
        players10.addElement("");
                
        String[] names = TeamManagerBE.getTeamPlayerName(teamID);
        for (int i = 0; i < names.length; i++) {
            players1.addElement(names[i]);
            players2.addElement(names[i]);
            players3.addElement(names[i]);
            players4.addElement(names[i]);
            players5.addElement(names[i]);
            players6.addElement(names[i]);
            players7.addElement(names[i]);
            players8.addElement(names[i]);
            players9.addElement(names[i]);
            players10.addElement(names[i]);

        }

        GoalScorerCombo1.setModel(players1);
        GoalScorerCombo2.setModel(players2);
        GoalScorerCombo3.setModel(players3);
        GoalScorerCombo4.setModel(players4);
        GoalScorerCombo5.setModel(players5);

        AssisterCombo1.setModel(players6);
        AssisterCombo2.setModel(players7);
        AssisterCombo3.setModel(players8);
        AssisterCombo4.setModel(players9);
        AssisterCombo5.setModel(players10);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        GoalScorerCombo1 = new javax.swing.JComboBox<>();
        AssisterCombo1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        goalSpinner1 = new javax.swing.JSpinner();
        assistSpinner1 = new javax.swing.JSpinner();
        GoalScorerCombo2 = new javax.swing.JComboBox<>();
        GoalScorerCombo3 = new javax.swing.JComboBox<>();
        GoalScorerCombo4 = new javax.swing.JComboBox<>();
        GoalScorerCombo5 = new javax.swing.JComboBox<>();
        AssisterCombo2 = new javax.swing.JComboBox<>();
        AssisterCombo3 = new javax.swing.JComboBox<>();
        AssisterCombo4 = new javax.swing.JComboBox<>();
        AssisterCombo5 = new javax.swing.JComboBox<>();
        goalSpinner2 = new javax.swing.JSpinner();
        goalSpinner3 = new javax.swing.JSpinner();
        goalSpinner4 = new javax.swing.JSpinner();
        goalSpinner5 = new javax.swing.JSpinner();
        assistSpinner2 = new javax.swing.JSpinner();
        assistSpinner3 = new javax.swing.JSpinner();
        assistSpinner4 = new javax.swing.JSpinner();
        assistSpinner5 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LocationCombo = new javax.swing.JComboBox<>();
        TeamACombo = new javax.swing.JComboBox<>();
        TeamBCombo = new javax.swing.JComboBox<>();
        TeamAGoals = new javax.swing.JSpinner();
        TeamBGoals = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Match Result");

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        GoalScorerCombo1.setBackground(new java.awt.Color(0, 0, 51));
        GoalScorerCombo1.setForeground(new java.awt.Color(255, 255, 255));
        GoalScorerCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AssisterCombo1.setBackground(new java.awt.Color(0, 0, 51));
        AssisterCombo1.setForeground(new java.awt.Color(255, 255, 255));
        AssisterCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Goal Scorers");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Goal Assisters");

        goalSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                goalSpinner1StateChanged(evt);
            }
        });

        assistSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                assistSpinner1StateChanged(evt);
            }
        });

        GoalScorerCombo2.setBackground(new java.awt.Color(0, 0, 51));
        GoalScorerCombo2.setForeground(new java.awt.Color(255, 255, 255));
        GoalScorerCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GoalScorerCombo3.setBackground(new java.awt.Color(0, 0, 51));
        GoalScorerCombo3.setForeground(new java.awt.Color(255, 255, 255));
        GoalScorerCombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GoalScorerCombo4.setBackground(new java.awt.Color(0, 0, 51));
        GoalScorerCombo4.setForeground(new java.awt.Color(255, 255, 255));
        GoalScorerCombo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GoalScorerCombo5.setBackground(new java.awt.Color(0, 0, 51));
        GoalScorerCombo5.setForeground(new java.awt.Color(255, 255, 255));
        GoalScorerCombo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AssisterCombo2.setBackground(new java.awt.Color(0, 0, 51));
        AssisterCombo2.setForeground(new java.awt.Color(255, 255, 255));
        AssisterCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AssisterCombo3.setBackground(new java.awt.Color(0, 0, 51));
        AssisterCombo3.setForeground(new java.awt.Color(255, 255, 255));
        AssisterCombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AssisterCombo4.setBackground(new java.awt.Color(0, 0, 51));
        AssisterCombo4.setForeground(new java.awt.Color(255, 255, 255));
        AssisterCombo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AssisterCombo5.setBackground(new java.awt.Color(0, 0, 51));
        AssisterCombo5.setForeground(new java.awt.Color(255, 255, 255));
        AssisterCombo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        goalSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                goalSpinner2StateChanged(evt);
            }
        });

        goalSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                goalSpinner3StateChanged(evt);
            }
        });

        goalSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                goalSpinner4StateChanged(evt);
            }
        });

        goalSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                goalSpinner5StateChanged(evt);
            }
        });

        assistSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                assistSpinner2StateChanged(evt);
            }
        });

        assistSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                assistSpinner3StateChanged(evt);
            }
        });

        assistSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                assistSpinner4StateChanged(evt);
            }
        });

        assistSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                assistSpinner5StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(GoalScorerCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(goalSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GoalScorerCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GoalScorerCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goalSpinner3)
                            .addComponent(goalSpinner4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(GoalScorerCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(goalSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(GoalScorerCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(goalSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AssisterCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssisterCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssisterCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssisterCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssisterCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(assistSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(assistSpinner2)
                            .addComponent(assistSpinner3)
                            .addComponent(assistSpinner4)
                            .addComponent(assistSpinner5))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AssisterCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assistSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AssisterCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assistSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AssisterCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assistSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AssisterCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assistSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AssisterCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assistSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoalScorerCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goalSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoalScorerCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goalSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoalScorerCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goalSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoalScorerCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goalSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoalScorerCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goalSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Location");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Team A");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Team B");

        LocationCombo.setBackground(new java.awt.Color(0, 0, 51));
        LocationCombo.setForeground(new java.awt.Color(255, 255, 255));
        LocationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TeamACombo.setBackground(new java.awt.Color(0, 0, 51));
        TeamACombo.setForeground(new java.awt.Color(255, 255, 255));
        TeamACombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TeamACombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamAComboActionPerformed(evt);
            }
        });

        TeamBCombo.setBackground(new java.awt.Color(0, 0, 51));
        TeamBCombo.setForeground(new java.awt.Color(255, 255, 255));
        TeamBCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TeamAGoals.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TeamAGoalsStateChanged(evt);
            }
        });

        TeamBGoals.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TeamBGoalsStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Goals for Team B");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Goals for Team A");

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TeamBGoals))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TeamAGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LocationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TeamACombo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TeamBCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabel1)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LocationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TeamACombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeamAGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TeamBCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeamBGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        HomeScreen Info = new HomeScreen();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TeamAComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamAComboActionPerformed
        try {
            // TODO add your handling code here:
            updatePlayers();
        } catch (SQLException ex) {
            Logger.getLogger(AddMatchResults.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddMatchResults.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TeamAComboActionPerformed

    private void goalSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_goalSpinner1StateChanged
        // TODO add your handling code here:
        int min = 0;
        int goal1SpinnerValue = (int) goalSpinner1.getValue();

        if (goal1SpinnerValue < min) {
            goalSpinner1.setValue(min);
        }

    }//GEN-LAST:event_goalSpinner1StateChanged

    private void goalSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_goalSpinner2StateChanged
        // TODO add your handling code here:
        int min = 0;
        int goal2SpinnerValue = (int) goalSpinner2.getValue();

        if (goal2SpinnerValue < min) {
            goalSpinner2.setValue(min);
        }
    }//GEN-LAST:event_goalSpinner2StateChanged

    private void goalSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_goalSpinner3StateChanged
        // TODO add your handling code here:

        int min = 0;
        int goal3SpinnerValue = (int) goalSpinner3.getValue();

        if (goal3SpinnerValue < min) {
            goalSpinner3.setValue(min);
        }
    }//GEN-LAST:event_goalSpinner3StateChanged

    private void goalSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_goalSpinner4StateChanged
        // TODO add your handling code here:
        int min = 0;
        int goal4SpinnerValue = (int) goalSpinner4.getValue();

        if (goal4SpinnerValue < min) {
            goalSpinner4.setValue(min);
        }
    }//GEN-LAST:event_goalSpinner4StateChanged

    private void goalSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_goalSpinner5StateChanged
        // TODO add your handling code here:
        int min = 0;
        int goal5SpinnerValue = (int) goalSpinner5.getValue();

        if (goal5SpinnerValue < min) {
            goalSpinner5.setValue(min);
        }
    }//GEN-LAST:event_goalSpinner5StateChanged

    private void assistSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_assistSpinner1StateChanged
        // TODO add your handling code here:
        int min = 0;
        int assistlSpinnerValue1 = (int) assistSpinner2.getValue();

        if (assistlSpinnerValue1 < min) {
            assistSpinner2.setValue(min);
        }
    }//GEN-LAST:event_assistSpinner1StateChanged

    private void assistSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_assistSpinner2StateChanged
        // TODO add your handling code here:
        int min = 0;
        int assist2SpinnerValue1 = (int) assistSpinner3.getValue();

        if (assist2SpinnerValue1 < min) {
            assistSpinner3.setValue(min);
        }
    }//GEN-LAST:event_assistSpinner2StateChanged

    private void assistSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_assistSpinner3StateChanged
        // TODO add your handling code here:
        int min = 0;
        int assist3SpinnerValue1 = (int) assistSpinner4.getValue();

        if (assist3SpinnerValue1 < min) {
            assistSpinner4.setValue(min);
        }
    }//GEN-LAST:event_assistSpinner3StateChanged

    private void assistSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_assistSpinner4StateChanged
        // TODO add your handling code here:

        int min = 0;
        int assist4SpinnerValue1 = (int) assistSpinner5.getValue();

        if (assist4SpinnerValue1 < min) {
            assistSpinner5.setValue(min);
        }
    }//GEN-LAST:event_assistSpinner4StateChanged

    private void assistSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_assistSpinner5StateChanged
        // TODO add your handling code here:
        int min = 0;
        int assist5SpinnerValue1 = (int) assistSpinner1.getValue();

        if (assist5SpinnerValue1 < min) {
            assistSpinner1.setValue(min);
        }
    }//GEN-LAST:event_assistSpinner5StateChanged

    private void TeamAGoalsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TeamAGoalsStateChanged
        // TODO add your handling code here:
        int min = 0;
        int TeamAGoalsVal = (int) TeamAGoals.getValue();

        if (TeamAGoalsVal < min) {
            TeamAGoals.setValue(min);
        }
    }//GEN-LAST:event_TeamAGoalsStateChanged

    private void TeamBGoalsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TeamBGoalsStateChanged
        // TODO add your handling code here:
        int min = 0;
        int TeamBGoalsVal = (int) TeamBGoals.getValue();

        if (TeamBGoalsVal < min) {
            TeamBGoals.setValue(min);
        }
    }//GEN-LAST:event_TeamBGoalsStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:

            String location = (String) LocationCombo.getSelectedItem();
            String teamA = (String) TeamACombo.getSelectedItem();
            String teamB = (String) TeamBCombo.getSelectedItem();
            int teamAGoals = (int) TeamAGoals.getValue();
            int teamBGoals = (int) TeamBGoals.getValue();

            GameManagerBE.addGame(location, teamB, teamB,teamAGoals, teamBGoals);

            String gameID = GameManagerBE.getGameID(location, teamB, teamB, teamBGoals);

            //// This is to get the goal scorers(add is to stats)
            String goalfullName1 = (String) GoalScorerCombo1.getSelectedItem();
            int goals1 = (int) goalSpinner1.getValue();
            GameManagerBE.addGameGoals(gameID, goalfullName1, goals1);

            String goalfullName2 = (String) GoalScorerCombo2.getSelectedItem();
            int goals2 = (int) goalSpinner2.getValue();
            GameManagerBE.addGameGoals(gameID, goalfullName2, goals2);

            String goalfullName3 = (String) GoalScorerCombo3.getSelectedItem();
            int goals3 = (int) goalSpinner3.getValue();
            GameManagerBE.addGameGoals(gameID, goalfullName3, goals3);

            String goalfullName4 = (String) GoalScorerCombo4.getSelectedItem();
            int goals4 = (int) goalSpinner4.getValue();
            GameManagerBE.addGameGoals(gameID, goalfullName4, goals4);

            String goalfullName5 = (String) GoalScorerCombo5.getSelectedItem();
            int goals5 = (int) goalSpinner5.getValue();
            GameManagerBE.addGameGoals(gameID, goalfullName5, goals5);

            ///// This is for the asssisters and how many assists the got(will be added to stats)
            String assistfullName1 = (String) AssisterCombo1.getSelectedItem();
            int assists1 = (int) assistSpinner1.getValue();
            GameManagerBE.addGameAssists(gameID, assistfullName1, assists1);

            String assistfullName2 = (String) AssisterCombo2.getSelectedItem();
            int assists2 = (int) assistSpinner2.getValue();
            GameManagerBE.addGameAssists(gameID, assistfullName2, assists2);

            String assistfullName3 = (String) AssisterCombo3.getSelectedItem();
            int assists3 = (int) assistSpinner3.getValue();
            GameManagerBE.addGameAssists(gameID, assistfullName3, assists3);

            String assistfullName4 = (String) AssisterCombo4.getSelectedItem();
            int assists4 = (int) assistSpinner4.getValue();
            GameManagerBE.addGameAssists(gameID, assistfullName4, assists4);

            String assistfullName5 = (String) AssisterCombo5.getSelectedItem();
            int assists5 = (int) assistSpinner5.getValue();
            GameManagerBE.addGameAssists(gameID, assistfullName5, assists5);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddMatchResults.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddMatchResults.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMatchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMatchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMatchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMatchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMatchResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AssisterCombo1;
    private javax.swing.JComboBox<String> AssisterCombo2;
    private javax.swing.JComboBox<String> AssisterCombo3;
    private javax.swing.JComboBox<String> AssisterCombo4;
    private javax.swing.JComboBox<String> AssisterCombo5;
    private javax.swing.JComboBox<String> GoalScorerCombo1;
    private javax.swing.JComboBox<String> GoalScorerCombo2;
    private javax.swing.JComboBox<String> GoalScorerCombo3;
    private javax.swing.JComboBox<String> GoalScorerCombo4;
    private javax.swing.JComboBox<String> GoalScorerCombo5;
    private javax.swing.JComboBox<String> LocationCombo;
    private javax.swing.JComboBox<String> TeamACombo;
    private javax.swing.JSpinner TeamAGoals;
    private javax.swing.JComboBox<String> TeamBCombo;
    private javax.swing.JSpinner TeamBGoals;
    private javax.swing.JSpinner assistSpinner1;
    private javax.swing.JSpinner assistSpinner2;
    private javax.swing.JSpinner assistSpinner3;
    private javax.swing.JSpinner assistSpinner4;
    private javax.swing.JSpinner assistSpinner5;
    private javax.swing.JSpinner goalSpinner1;
    private javax.swing.JSpinner goalSpinner2;
    private javax.swing.JSpinner goalSpinner3;
    private javax.swing.JSpinner goalSpinner4;
    private javax.swing.JSpinner goalSpinner5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
